import {catalog} from './catalog.js';
import {percentage,status,sessionKey,mergeRecords,makeSession,parseLegacy,toLegacy,validateRecords} from './core.js';
const {students,courses,routine}=catalog, days=['Saturday','Sunday','Monday','Tuesday','Wednesday'];
const $=s=>document.querySelector(s), esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const icons={dashboard:'M3 3h7v7H3z M14 3h7v7h-7z M3 14h7v7H3z M14 14h7v7h-7z',check:'M5 12l4 4L19 6',register:'M9 5H5v16h14V5h-4 M9 3h6v4H9z M8 13l2 2 5-5',students:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2 M9 3a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M18 8a3 3 0 0 1 0 6 M22 21v-2a4 4 0 0 0-3-4',calendar:'M4 5h16v16H4z M8 3v4 M16 3v4 M4 10h16 M8 14h2 M14 14h2',report:'M4 3h16v18H4z M8 16v-4 M12 16V8 M16 16v-6',settings:'M12 8a4 4 0 1 0 0 8 4 4 0 0 0 0-8 M12 2v3 M12 19v3 M2 12h3 M19 12h3 M5 5l2 2 M17 17l2 2 M5 19l2-2 M17 7l2-2',arrow:'M5 12h14 M14 7l5 5-5 5',download:'M12 3v12 M7 10l5 5 5-5 M4 16v5h16v-5',book:'M12 6c-3-3-7-3-10-2v15c4-1 7-1 10 2 3-3 7-3 10-2V4c-3-1-7-1-10 2z M12 6v15',close:'M6 6l12 12 M18 6L6 18',clock:'M12 8v5l3 2 M12 2a10 10 0 1 0 0 20 10 10 0 0 0 0-20',leaf:'M20 3C8 2 2 8 6 16c8 4 14-2 14-13z M4 21L15 10',plus:'M12 5v14 M5 12h14'};
const icon=n=>`<svg viewBox="0 0 24 24" aria-hidden="true"><path d="${icons[n]||icons.check}"/></svg>`;
const today=()=>{const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;};
const legacyDate=d=>d.split('-').reverse().join('-');
const STORAGE='rollcall-records-v1';
let records=[],loadError='',api='',token='',demo=false;
try{records=validateRecords(JSON.parse(localStorage.getItem(STORAGE)||'[]'));api=localStorage.getItem('rollcall-api')||'';token=sessionStorage.getItem('rollcall-token')||'';}catch(e){loadError='Saved data could not be read. Export or restore a valid backup from Data & settings.';}
let view='dashboard',day=days.includes(new Date().toLocaleDateString('en-US',{weekday:'long'}))?new Date().toLocaleDateString('en-US',{weekday:'long'}):'Saturday',periodIndex=routine.findIndex(p=>p.day===day),date=today(),marks={},search='',course=courses[0].code,filter='all',busy=false;
let connected=false, candidateApi='';
const navs=[['dashboard','Overview','dashboard'],['attendance','Take attendance','register'],['students','Students','students'],['routine','Weekly routine','calendar'],['reports','Reports','report'],['settings','Data & settings','settings']];
function toast(msg,error=false){const el=$('#toast');el.textContent=msg;el.className='show'+(error?' error':'');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.className='',6000);}
function initials(name){return name.split(' ').filter(w=>w!=='Md.').slice(0,2).map(s=>s[0]).join('');}
function studentCell(s){return `<div class="studentcell"><span class="avatar color${s.sl%4}">${initials(s.name)}</span><div><strong>${esc(s.name)}</strong><small>${s.id}</small></div></div>`;}
function badge(p){let s=status(p);return `<span class="badge ${s==='At Risk'?'risk':s.toLowerCase()}">● ${s}</span>`;}
function progress(p){return `<div class="progress"><span class="track"><i style="width:${p}%"></i></span>${p.toFixed(1)}%</div>`;}
function options(){return courses.map(c=>`<option value="${c.code}" ${course===c.code?'selected':''}>${c.code} · ${c.title}</option>`).join('');}
function head(title,subtitle,buttons=''){return `<div class="pageheading"><div><div class="eyebrow">Autumn 2025 · Section 1AM</div><h1>${title}</h1><p class="subtitle">${subtitle}</p></div><div class="actions">${buttons}</div></div>`;}
function stat(label,val,sub,ic){return `<div class="stat"><div class="statlabel">${label}${icon(ic)}</div><div class="statvalue">${val}</div><small>${sub}</small></div>`;}
function recordedRate(rows){return rows.length?rows.filter(r=>r.present).length/rows.length*100:0;}
function render(){
 const nav=navs.find(n=>n[0]===view);
 $('#app').innerHTML=`<div class="shell"><aside class="sidebar"><div class="brand"><span class="brandmark">${icon('check')}</span><div>rollcall<span style="color:#9dbb75">.</span><small>ATTENDANCE STUDIO</small></div></div><div class="workspace"><span class="avatar">1A</span><div><strong>CSE Department</strong><small>Section 1AM · 45 students</small></div></div><p class="navlabel">WORKSPACE</p><nav class="nav" aria-label="Main navigation">${navs.map(([v,t,i])=>`<button data-nav="${v}" class="${view===v?'active':''}" ${view===v?'aria-current="page"':''}>${icon(i)}${t}${v==='students'?'<span class="count">45</span>':''}</button>`).join('')}</nav><div class="sidebarbottom"><div class="note">${icon('leaf')}<strong>Small check-ins. Big progress.</strong>A little consistency makes a lasting difference.</div><div class="identity"><span class="avatar">TK</span><div>Tahasanur Karim<small>Attendance workspace</small></div></div></div></aside><main class="main"><header class="topbar"><div class="breadcrumb">Workspace <strong>/ &nbsp; ${nav[1]}</strong></div><div class="topright"><span class="mode">${demo?'Sample preview':connected?'Shared workspace':'Saved on this browser'}</span><button class="iconbtn" data-nav="settings" aria-label="Open data settings">${icon('settings')}</button><span class="avatar">1A</span></div></header><div class="content">${loadError?`<div class="notice">${esc(loadError)}</div>`:''}${demo?'<div class="notice">Sample preview — attendance below is fictional and stays separate from your records. <button class="textbutton" data-action="exitDemo">Exit preview →</button></div>':''}${({dashboard:dashboard,attendance:attendance,students:studentsPage,routine:routinePage,reports:reportsPage,settings:settingsPage}[view])()}<footer class="footer"><span>Thoughtfully built for every class.</span><span>Rollcall · Powered by your original attendance rules</span></footer></div></main></div>`;
 bind();
}
function dashboard(){
 const sessions=new Set(records.map(sessionKey)).size;
 const weekday=new Date().toLocaleDateString('en-US',{weekday:'long'}), scheduled=routine.filter(p=>p.day===weekday);
 const upcoming=scheduled.length?scheduled:routine.filter(p=>p.day==='Saturday');
 return head('Your class, at a glance.','A clear picture of attendance. More time for what matters.',`<button data-action="export">${icon('download')}Export data</button><button class="primary" data-nav="attendance">${icon('plus')}Take attendance</button>`)+
 `<section class="hero"><div><div class="eyebrow">A LITTLE CONSISTENCY GOES A LONG WAY</div><h2>Every student. Every class.</h2><p>Keep attendance simple, spot progress early, and give every student the attention they deserve.</p><button data-nav="attendance">Start a class register &nbsp; →</button></div><div class="heroart"><div class="ring">${icon('register')}</div></div></section>`+
 `<section class="stats">${stat('Total students','45','<span>●</span> Active class roster','students')}${stat('Active courses','8','23 periods every week','book')}${stat('Sessions recorded',sessions,`${records.length} attendance entries`,'calendar')}${stat('Recorded presence',records.length?recordedRate(records).toFixed(1)+'%':'—','Across recorded entries only','report')}</section>`+
 `<div class="grid"><section class="panel"><div class="panelhead"><div><h2>Attendance by course</h2><p>Present entries as a share of recorded entries</p></div><span class="chip">All records</span></div><div class="chart" role="img" aria-label="Recorded presence by course">${courses.map(c=>{const rows=records.filter(r=>r.courseCode===c.code),p=recordedRate(rows);return `<div class="barcol"><span>${rows.length?p.toFixed(0)+'%':'—'}</span><div class="bar" style="height:${p*.8+2}%" title="${c.code}: ${rows.length?p.toFixed(1)+'%':'No records'}"></div></div>`;}).join('')}</div><div class="chartlabels">${courses.map(c=>`<span>${c.code.replace('-','<br>')}</span>`).join('')}</div><div class="chartlegend"><i class="dot"></i>${records.length?'Recorded presence · not the fixed-total semester score':'Your chart will grow as you record classes.'}</div></section><section class="panel"><div class="panelhead"><div><h2>${scheduled.length?"Today's classes":'Next teaching day'}</h2><p>${scheduled.length?weekday:'Saturday'} · Weekly routine</p></div><button class="textbutton" data-nav="routine">View all →</button></div>${upcoming.slice(0,3).map(p=>`<div class="scheduleitem"><div class="time">${p.startTime}<br><span>${p.endTime}</span></div><div class="courseicon">${icon('book')}</div><div><h3>${p.courseCode}</h3><p>${courses.find(c=>c.code===p.courseCode).title}</p></div><button data-period="${routine.indexOf(p)}" aria-label="Take attendance for ${p.courseCode} at ${p.startTime}">${icon('arrow')}</button></div>`).join('')}</section></div>`+
 `<section class="panel"><div class="panelhead"><div><h2>Student snapshot</h2><p>${esc(course)} · Semester attendance against the planned course total</p></div><button class="textbutton" data-nav="students">All students →</button></div>${studentTable(students.slice(0,5))}</section>`+(!records.length?'<div class="notice">Your workspace starts with no attendance records. Take your first class, import a C++ data file, or <button class="textbutton" data-action="demo">explore a fictional sample →</button></div>':'');
}
function studentTable(list){return `<div class="tablewrap"><table><thead><tr><th>Student</th><th>Present / Planned</th><th>Semester attendance</th><th>Status</th><th></th></tr></thead><tbody>${list.length?list.map(s=>{const p=percentage(records,s.id,course),n=records.filter(r=>r.studentId===s.id&&r.courseCode===course&&r.present).length;return `<tr><td>${studentCell(s)}</td><td>${n} <span style="color:#9ba58e">/ ${courses.find(c=>c.code===course).totalClasses}</span></td><td>${progress(p)}</td><td>${badge(p)}</td><td><button class="textbutton" data-student="${s.id}">View profile →</button></td></tr>`;}).join(''):'<tr><td colspan="5" class="empty">No students match your search.</td></tr>'}</tbody></table></div>`;}
function studentsPage(){return head('A little attention for everyone.','Find a student and understand their progress, course by course.')+`<div class="notice">Semester attendance = present classes ÷ planned classes (48, or 32 for Ethics). Status: ≥85% Excellent · ≥70% Good · ≥60% Warning · below 60% At Risk. Early-semester scores will naturally be low.</div><section class="panel"><div class="toolbar"><input class="search" id="search" aria-label="Search students" placeholder="Search by name or student ID…" value="${esc(search)}"><select id="course" aria-label="Course">${options()}</select><select id="filter" aria-label="Attendance status">${['all','Excellent','Good','Warning','At Risk'].map(v=>`<option ${filter===v?'selected':''} value="${v}">${v==='all'?'All statuses':v}</option>`).join('')}</select></div><div id="studentResults">${studentTable(filteredStudents())}</div></section>`;}
function filteredStudents(){return students.filter(s=>(s.name+' '+s.id).toLowerCase().includes(search.toLowerCase())&&(filter==='all'||status(percentage(records,s.id,course))===filter));}
function sessionRecords(){const p=routine[periodIndex];return records.filter(r=>r.courseCode===p.courseCode&&r.timeSlot===p.startTime&&r.date===legacyDate(date));}
function attendance(){const saved=sessionRecords(),locked=saved.length>0,p=routine[periodIndex];if(locked)marks=Object.fromEntries(saved.map(r=>[r.studentId,r.present]));return head('Make every class count.','Choose your class, mark the roster, and save once.')+`<section class="panel"><div class="filters"><label>Routine day<select id="day">${days.map(d=>`<option ${day===d?'selected':''}>${d}</option>`).join('')}</select></label><label>Class period<select id="period">${routine.map((p,i)=>p.day===day?`<option value="${i}" ${i===periodIndex?'selected':''}>${p.startTime} – ${p.endTime} · ${p.courseCode}</option>`:'').join('')}</select></label><label>Class date<input id="date" type="date" value="${date}" min="1900-01-01" max="9999-12-31" required></label></div><p class="hint">${esc(courses.find(c=>c.code===p.courseCode).title)} · You may select a different date for a rescheduled class, just like the C++ system.</p></section>${locked?'<div class="notice">This session already has attendance records. It is read-only to prevent duplicates.</div>':''}<section class="panel"><div class="toolbar"><input class="search" id="search" aria-label="Search roster" placeholder="Find a student…" value="${esc(search)}"><button data-mark-all="true" ${locked?'disabled':''}>✓ All present</button><button data-mark-all="false" ${locked?'disabled':''}>All absent</button><span class="registersummary" id="counts"></span></div><div class="tablewrap"><table><thead><tr><th>#</th><th>Student</th><th>Attendance</th></tr></thead><tbody id="roster">${rosterRows(locked)}</tbody></table></div></section><div class="savebar"><div><strong>${p.courseCode} · ${legacyDate(date)}</strong><p>${locked?'Saved session · changes are locked':'Unsaved marks stay in this session until you leave.'}</p></div><button class="primary" id="save" ${locked||busy||loadError?'disabled':''}>${locked?'Attendance saved':busy?'Saving…':'Save attendance →'}</button></div><div style="height:24px"></div>`;}
function rosterRows(locked){const list=students.filter(s=>(s.name+' '+s.id).toLowerCase().includes(search.toLowerCase()));return list.length?list.map(s=>`<tr><td style="color:#9aa48c">${String(s.sl).padStart(2,'0')}</td><td>${studentCell(s)}</td><td><div class="mark"><button class="present ${marks[s.id]===true?'selected':''}" aria-pressed="${marks[s.id]===true}" aria-label="${s.id} present" data-mark="${s.id}" data-value="true" ${locked?'disabled':''}>✓ Present</button><button class="absent ${marks[s.id]===false?'selected':''}" aria-pressed="${marks[s.id]===false}" aria-label="${s.id} absent" data-mark="${s.id}" data-value="false" ${locked?'disabled':''}>− Absent</button></div></td></tr>`).join(''):'<tr><td colspan="3" class="empty">No matching students.</td></tr>';}
function counts(){if($('#counts'))$('#counts').textContent=`${Object.values(marks).filter(v=>v).length} present · ${Object.values(marks).filter(v=>!v).length} absent · ${45-Object.keys(marks).length} unmarked`;}
function routinePage(){return head('A rhythm for your week.','Your original 23 class periods, from Saturday to Wednesday.',`<button data-action="print">${icon('download')}Print routine</button>`)+`<div class="weekgrid">${days.map(d=>`<section class="daycolumn"><h3>${d} <span style="color:#9aa48c;font-weight:400">/ ${routine.filter(p=>p.day===d).length}</span></h3>${routine.map((p,i)=>p.day===d?`<article class="classcard"><small>${p.startTime} – ${p.endTime}</small><h3>${p.courseCode}</h3><p>${courses.find(c=>c.code===p.courseCode).title}</p><button data-period="${i}">Take attendance →</button></article>`:'').join('')}</section>`).join('')}</div><div style="height:25px"></div>`;}
function reportsPage(){const grouped=Object.groupBy(records,sessionKey);return head('The full picture.','Review saved sessions and export your semester report.',`<button data-action="report">${icon('download')}Export report CSV</button><button data-action="print">Print report</button>`)+`<section class="panel"><div class="panelhead"><div><h2>Semester attendance matrix</h2><p>Each value uses the original fixed course total.</p></div><span class="chip">45 students · 8 courses</span></div><div class="tablewrap"><table><thead><tr><th>Student</th>${courses.map(c=>`<th>${c.code}</th>`).join('')}</tr></thead><tbody>${students.map(s=>`<tr><td>${studentCell(s)}</td>${courses.map(c=>`<td>${percentage(records,s.id,c.code).toFixed(1)}%</td>`).join('')}</tr>`).join('')}</tbody></table></div></section><section class="panel"><div class="panelhead"><h2>Saved sessions</h2><span class="chip">${Object.keys(grouped).length} sessions</span></div>${records.length?`<div class="tablewrap"><table><thead><tr><th>Course</th><th>Date</th><th>Period</th><th>Present</th><th>Absent</th><th>Completeness</th></tr></thead><tbody>${Object.values(grouped).sort((a,b)=>b[0].date.split('-').reverse().join('').localeCompare(a[0].date.split('-').reverse().join(''))).map(rows=>`<tr><td>${rows[0].courseCode}</td><td>${rows[0].date}</td><td>${rows[0].timeSlot}</td><td>${rows.filter(r=>r.present).length}</td><td>${rows.filter(r=>!r.present).length}</td><td>${rows.length}/45</td></tr>`).join('')}</tbody></table></div>`:'<div class="empty">No sessions yet. Your saved classes will appear here.</div>'}</section>`;}
function settingsPage(){return head('Your data, in good hands.','Choose where records live, and keep a copy of your work.')+`<div class="settingsgrid"><section class="panel"><div class="panelhead"><h2>${icon('download')} Import & export</h2></div><div class="panelbody"><p>Move between the original C++ app and Rollcall using <strong>attendance_data.txt</strong>. Import merges new records and rejects duplicates. Your data never goes into the public GitHub repository.</p><button data-action="export">Download C++ data file</button> <button data-action="backup">Download JSON backup</button><label>Import a C++ file or JSON backup<input id="import" type="file" accept=".txt,.json"></label><p>The repository’s old attendance.csv uses a different format and unmatched IDs. It is preserved in the source, but is not silently imported.</p></div></section><section class="panel"><div class="panelhead"><h2>${icon('settings')} Storage connection</h2><span class="chip">${connected?'Connected':'Browser local'}</span></div><div class="panelbody"><p>${connected?'Records are stored in your authenticated shared backend.':"Records stay in this browser, on this device. Clearing browser data removes them; download backups regularly. Connect the included backend to share records across devices."}</p><label>Backend URL<input id="api" type="url" placeholder="https://your-backend.example.com" value="${esc(api)}"></label><button class="primary" data-action="connect">${connected?'Reconnect':'Connect & sign in'}</button>${connected?'<button data-action="disconnect">Disconnect</button>':''}<p>Connecting does not upload local data automatically. Export it first, then import after connecting.</p></div></section><section class="panel"><div class="panelhead"><h2>The original engine</h2></div><div class="panelbody"><p>45 students. Eight courses. 23 weekly periods.<br>Present or absent, individual or bulk marking.<br>Unique student + course + date + time slot.<br>Percentage = present ÷ planned classes, capped at 100%.<br>Excellent ≥85% · Good ≥70% · Warning ≥60% · At Risk &lt;60%.</p><a href="https://github.com/tahasanurkarim-pixel/Attendence-Tracking" target="_blank" rel="noopener">Explore the source code →</a></div></section><section class="panel"><div class="panelhead"><h2>Explore before your first class</h2></div><div class="panelbody"><p>Try a fictional sample to see charts and reports in action. Sample attendance is never mixed with your saved records.</p><button data-action="${demo?'exitDemo':'demo'}">${demo?'Exit sample preview':'Open sample preview'}</button></div></section></div>`;}
function profile(id){const s=students.find(s=>s.id===id);$('#dialog').innerHTML=`<div class="modalhead"><div>${studentCell(s)}</div><button class="iconbtn" data-close aria-label="Close profile">${icon('close')}</button></div><div class="reportmeta">Course-by-course attendance · fixed semester totals</div><div class="tablewrap"><table><thead><tr><th>Course</th><th>Present / Planned</th><th>Attendance</th><th>Status</th></tr></thead><tbody>${courses.map(c=>{const p=percentage(records,id,c.code),n=records.filter(r=>r.studentId===id&&r.courseCode===c.code&&r.present).length;return `<tr><td>${c.code}</td><td>${n} / ${c.totalClasses}</td><td>${progress(p)}</td><td>${badge(p)}</td></tr>`;}).join('')}</tbody></table></div><p class="hint" style="padding-top:16px">Planned totals: 48 classes per course, 32 for Ethics and Morality.</p>`;$('#dialog').showModal();}
function download(name,text,type='text/plain'){const u=URL.createObjectURL(new Blob([text],{type})),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000);}
async function request(path,body,base=api,auth=token){const res=await fetch(base+path,{method:body===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...(auth?{Authorization:'Bearer '+auth}:{})},...(body===undefined?{}:{body:JSON.stringify(body)}),signal:AbortSignal.timeout(15000)});const data=await res.json();if(!res.ok)throw Error(data.error||'The server could not complete this request.');return data;}
async function saveRows(rows){if(demo)throw Error('Exit sample preview before saving attendance.');if(loadError)throw Error(loadError);if(connected){await request('/api/records',{records:rows});records=validateRecords((await request('/api/records')).records);}else{const write=()=>{const latest=validateRecords(JSON.parse(localStorage.getItem(STORAGE)||'[]'));const next=mergeRecords(latest,rows);localStorage.setItem(STORAGE,JSON.stringify(next));records=next;};if(navigator.locks)await navigator.locks.request(STORAGE,write);else write();}}
function navigate(v){if(view==='attendance'&&Object.keys(marks).length&&!sessionRecords().length&&v!==view&&!confirm('Leave this register? Unsaved marks will be discarded.'))return;view=v;search='';marks={};render();window.scrollTo(0,0);}
function bind(){counts();}
document.addEventListener('click',async e=>{const b=e.target.closest('button');if(!b||b.disabled)return;try{
 if(b.hasAttribute('data-close')){$('#dialog').close();return;}
 if(b.dataset.nav){navigate(b.dataset.nav);return;}
 if(b.dataset.student){profile(b.dataset.student);return;}
 if(b.dataset.period!==undefined){periodIndex=Number(b.dataset.period);day=routine[periodIndex].day;date=today();marks={};view='attendance';search='';render();window.scrollTo(0,0);return;}
 if(b.dataset.mark){marks[b.dataset.mark]=b.dataset.value==='true';$('#roster').innerHTML=rosterRows(false);counts();return;}
 if(b.dataset.markAll!==undefined){marks=Object.fromEntries(students.map(s=>[s.id,b.dataset.markAll==='true']));$('#roster').innerHTML=rosterRows(false);counts();return;}
 if(b.id==='save'){const rows=makeSession(records,routine[periodIndex],legacyDate(date),marks);busy=true;b.disabled=true;b.textContent='Saving…';try{await saveRows(rows);toast('Attendance saved for all 45 students.');}finally{busy=false;render();}return;}
 const a=b.dataset.action;
 if(a==='export')download('attendance_data.txt',toLegacy(records));
 if(a==='backup')download('rollcall-backup.json',JSON.stringify(records,null,2),'application/json');
 if(a==='report'){const quote=v=>'"'+String(v).replaceAll('"','""')+'"';download('semester-attendance.csv',[['Student ID','Name',...courses.map(c=>c.code+' (%)')],...students.map(s=>[s.id,s.name,...courses.map(c=>percentage(records,s.id,c.code).toFixed(1))])].map(row=>row.map(quote).join(',')).join('\r\n'),'text/csv');}
 if(a==='print')window.print();
 if(a==='demo'){demo=true;records=[];routine.forEach((p,i)=>{for(let week=0;week<8;week++){const d=new Date(2025,8,6+days.indexOf(p.day)+week*7);const dd=String(d.getDate()).padStart(2,'0')+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+d.getFullYear();students.forEach((s,j)=>records.push({studentId:s.id,courseCode:p.courseCode,date:dd,timeSlot:p.startTime,present:(j*7+i*3+week)%11>1}));}});view='dashboard';render();}
 if(a==='exitDemo'){demo=false;records=connected?validateRecords((await request('/api/records')).records):validateRecords(JSON.parse(localStorage.getItem(STORAGE)||'[]'));render();}
 if(a==='connect'){if(demo)throw Error('Exit sample preview before connecting.');const u=new URL($('#api').value);if(u.protocol!=='https:'&&!(u.protocol==='http:'&&['localhost','127.0.0.1'].includes(u.hostname)))throw Error('Use an HTTPS backend URL.');candidateApi=u.origin;$('#dialog').innerHTML=`<div class="modalhead"><h2>Sign in to your workspace</h2><button data-close class="iconbtn" aria-label="Close">${icon('close')}</button></div><form id="login" class="modalbody"><p>Connect to ${esc(candidateApi)} with the administrator password configured on your backend.</p><label>Administrator password<input name="password" type="password" autocomplete="current-password" required></label><button class="primary">Sign in</button><p id="loginError" role="alert"></p></form>`;$('#dialog').showModal();}
 if(a==='disconnect'){await request('/api/logout',{});token='';connected=false;sessionStorage.removeItem('rollcall-token');records=validateRecords(JSON.parse(localStorage.getItem(STORAGE)||'[]'));render();toast('Disconnected. Showing local records.');}
 }catch(err){toast(err.message,true);}});
document.addEventListener('input',e=>{if(e.target.id==='search'){search=e.target.value;if(view==='students')$('#studentResults').innerHTML=studentTable(filteredStudents());else $('#roster').innerHTML=rosterRows(sessionRecords().length>0);}});
document.addEventListener('change',async e=>{const el=e.target;try{if(['day','period','date'].includes(el.id)){if(Object.keys(marks).length&&!sessionRecords().length&&!confirm('Change class? Unsaved marks will be discarded.')){render();return;}if(el.id==='day'){day=el.value;periodIndex=routine.findIndex(p=>p.day===day);}if(el.id==='period')periodIndex=Number(el.value);if(el.id==='date')date=el.value;marks={};render();}if(el.id==='course'){course=el.value;render();}if(el.id==='filter'){filter=el.value;render();}if(el.id==='import'){const f=el.files[0];if(!f)return;if(f.size>20000000)throw Error('Choose a file smaller than 20 MB.');const text=await f.text(),rows=f.name.endsWith('.json')?validateRecords(JSON.parse(text)):parseLegacy(text);if(!rows.length)throw Error('The file has no attendance records.');if(confirm(`Import ${rows.length} records? Existing records will be kept; any duplicate rejects the whole import.`)){await saveRows(rows);render();toast(`${rows.length} records imported.`);}el.value='';}}catch(err){toast(err.message,true);}});
document.addEventListener('submit',async e=>{if(e.target.id!=='login')return;e.preventDefault();const button=e.target.querySelector('button');button.disabled=true;try{const result=await request('/api/login',{password:new FormData(e.target).get('password')},candidateApi,'');const shared=validateRecords((await request('/api/records',undefined,candidateApi,result.token)).records);api=candidateApi;token=result.token;records=shared;sessionStorage.setItem('rollcall-token',token);localStorage.setItem('rollcall-api',api);connected=true;loadError='';$('#dialog').close();render();toast('Connected to shared attendance storage.');}catch(err){$('#loginError').textContent=err.message;}finally{button.disabled=false;}});
window.addEventListener('beforeunload',e=>{if(view==='attendance'&&Object.keys(marks).length&&!sessionRecords().length){e.preventDefault();e.returnValue='';}});
window.addEventListener('storage',e=>{if(e.key===STORAGE&&!connected&&!demo){try{records=validateRecords(JSON.parse(e.newValue||'[]'));render();}catch{toast('Another tab saved invalid data. Please restore a backup.',true);}}});
render();
if(api&&token){request('/api/records').then(data=>{records=validateRecords(data.records);connected=true;render();}).catch(()=>toast('Backend session unavailable. Showing local records; reconnect in settings.',true));}
